defaults:
  - encoder: meds_code
  - query_projector: identity
  - retriever: static
  - retrieval_encoder: identity
  - fusion: replace
  - pooling: identity
  - head: linear
  - _self_

_target_: medrap.model.RetrievalAugmentedModel
