_target_: medrap.retrievers.InMemoryTopKRetriever
doc_key_embeddings:
  _target_: torch.FloatTensor
  _args_:
    - [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0]]
doc_tokens:
  _target_: torch.LongTensor
  _args_:
    - [[1, 2], [3, 4]]
doc_attention_mask:
  _target_: torch.BoolTensor
  _args_:
    - [[true, true], [true, true]]
k: 1
similarity: dot
