defaults:
  - config: MEDSTorchDataConfig
  - _self_

_target_: meds_torchdata.extensions.lightning_datamodule.Datamodule

config:
  max_seq_len: ${max_seq_len}
  static_inclusion_mode: INCLUDE

batch_size: 8
num_workers: 0
pin_memory: false
